Changing forward signature to explicit named variables
frostedoyster/torch_spex pull request #9
Opened 2023-06-16 16:04 UTC by agoscinski

As discussed in #8 the change to the forward signature

2023-07-11 21:41 UTC, agoscinski commented
First draft for changing forward signature to accept neighborlists. I removed the mask in the neighborlist creation, I am the opinion that the same effect of the mask can be achieved by turning off self_interaction. At the moment the test `test_finite_differences` fails, because I have not adapted it yet.

TODOs:
- I prefer to do change the pair indices adaptively during the collate_fn evoked by the DataLoader that using a structure_offset that makes a bit the usage for single structures cumbersome. I want to change it to this style
- include tests that have more than one frame
- include tests that have nonzero cell_shifts
- change finite difference to autograd.gradcheck

2023-07-17 17:28 UTC, agoscinski commented
I tried to put the computation of the direction vectors into tho computation of the Dataset, so it does not need to be recomputed each epoch, but there is a problem doing this when also having the option to batch arbitrary. The batched positions loose the connection to the direction vectors

```
positions --DataLoader--> batched_positions # because concatenating or slicing creates a new node in the autograd graph
   |
   |Dataset
   |
   --> direction_vectors --DataLoader--> batched_direction_vectors
```
So when backpropagating the direction vectors we cannot get the gradients from the batched positions but need the original positions. So The DataLoader returns in addition a list of positions, so one can access the gradients. @abmazitov raised the concern that autograd.grad might be compute multiple times the gradients when using a list. I registered a hook on the direction_vectors to see if they are recomputed using
```python
input_kwargs["direction_vectors"].retain_grad()
input_kwargs["direction_vectors"].register_hook(lambda _: print("USED"))
```
and could not find any recomputations of the gradients.

2023-07-19 10:05 UTC, abmazitov requested changes
I would suggest to rename `InMemoryNeighborList` to `InMemoryDataset` to avoid ambiguity with `TransformerNeighborList`. Everything else seems reasonable to me.

2023-07-19 14:55 UTC, agoscinski commented on tests/test_spherical_expansions.py
> +    dataset = InMemoryNeighborList(frames, transformers)
right, good catch, changed it

2023-07-19 15:40 UTC, merged